port: ":8080"
auth-secret: "mwyzkpemjwmprwcelfgxsgxaesihnymdypeovdwrtdgdtteibybzqiljzaawsjrgtzyoresfmowvrkkpepznltxhayyuxqzxcaelrvwheijssbslqcglejoyqunikpjj"
db:
  username: "tester"
  host : "localhost"
  port : "5432"
  dbname : "donchap"
  sslmode : "disable"
  password : "password"